name: GitHub Actions Demo 2
run-name: ${{ github.actor }} GH actions test 2
on: [push]
jobs:
  Second-Test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: make setup